/* Auto-generated by Tools/scripts/generate_opcode_h.py from Lib/opcode.py */
#ifndef Py_OPCODE_H
#define Py_OPCODE_H
#ifdef __cplusplus
extern "C" {
#endif


    /* Instruction opcodes for compiled code */
#define POP_TOP                   0
#define ROT_TWO                   1
#define ROT_THREE                 2
#define DUP_TOP                   3
#define DUP_TOP_TWO               4
#define ROT_FOUR                  5
#define NOP                       6
#define UNARY_POSITIVE            7
#define UNARY_NEGATIVE            8
#define UNARY_NOT                 9
#define UNARY_INVERT             10
#define BINARY_MATRIX_MULTIPLY   11
#define INPLACE_MATRIX_MULTIPLY  12
#define BINARY_POWER             13
#define BINARY_MULTIPLY          14
#define BINARY_MODULO            15
#define BINARY_ADD               16
#define BINARY_SUBTRACT          17
#define BINARY_SUBSCR            18
#define BINARY_FLOOR_DIVIDE      19
#define BINARY_TRUE_DIVIDE       20
#define INPLACE_FLOOR_DIVIDE     21
#define INPLACE_TRUE_DIVIDE      22
#define GET_LEN                  23
#define MATCH_MAPPING            24
#define MATCH_SEQUENCE           25
#define MATCH_KEYS               26
#define COPY_DICT_WITHOUT_KEYS   27
#define WITH_EXCEPT_START        28
#define GET_AITER                29
#define GET_ANEXT                30
#define BEFORE_ASYNC_WITH        31
#define END_ASYNC_FOR            32
#define INPLACE_ADD              33
#define INPLACE_SUBTRACT         34
#define INPLACE_MULTIPLY         35
#define INPLACE_MODULO           36
#define STORE_SUBSCR             37
#define DELETE_SUBSCR            38
#define BINARY_LSHIFT            39
#define BINARY_RSHIFT            40
#define BINARY_AND               41
#define BINARY_XOR               42
#define BINARY_OR                43
#define INPLACE_POWER            44
#define GET_ITER                 45
#define GET_YIELD_FROM_ITER      46
#define PRINT_EXPR               47
#define LOAD_BUILD_CLASS         48
#define YIELD_FROM               49
#define GET_AWAITABLE            50
#define LOAD_ASSERTION_ERROR     51
#define INPLACE_LSHIFT           52
#define INPLACE_RSHIFT           53
#define INPLACE_AND              54
#define INPLACE_XOR              55
#define INPLACE_OR               56
#define LIST_TO_TUPLE            57
#define RETURN_VALUE             58
#define IMPORT_STAR              59
#define SETUP_ANNOTATIONS        60
#define YIELD_VALUE              61
#define POP_BLOCK                62
#define POP_EXCEPT               63
#define HAVE_ARGUMENT            64
#define RERAISE                  64
#define STORE_NAME               65
#define DELETE_NAME              66
#define UNPACK_SEQUENCE          67
#define FOR_ITER                 68
#define UNPACK_EX                69
#define STORE_ATTR               70
#define DELETE_ATTR              71
#define STORE_GLOBAL             72
#define DELETE_GLOBAL            73
#define LOAD_CONST               74
#define LOAD_NAME                75
#define BUILD_TUPLE              76
#define BUILD_LIST               77
#define BUILD_SET                78
#define BUILD_MAP                79
#define LOAD_ATTR                80
#define COMPARE_OP               81
#define IMPORT_NAME              82
#define IMPORT_FROM              83
#define JUMP_FORWARD             84
#define JUMP_IF_FALSE_OR_POP     85
#define JUMP_IF_TRUE_OR_POP      86
#define JUMP_ABSOLUTE            87
#define POP_JUMP_IF_FALSE        88
#define POP_JUMP_IF_TRUE         89
#define LOAD_GLOBAL              90
#define IS_OP                    91
#define CONTAINS_OP              92
#define JUMP_IF_NOT_EXC_MATCH    93
#define SETUP_FINALLY            94
#define LOAD_FAST                95
#define STORE_FAST               96
#define DELETE_FAST              97
#define RAISE_VARARGS            98
#define CALL_FUNCTION            99
#define MAKE_FUNCTION           100
#define BUILD_SLICE             101
#define LOAD_CLOSURE            102
#define LOAD_DEREF              103
#define STORE_DEREF             104
#define DELETE_DEREF            105
#define CALL_FUNCTION_KW        106
#define CALL_FUNCTION_EX        107
#define SETUP_WITH              108
#define EXTENDED_ARG            109
#define LIST_APPEND             110
#define SET_ADD                 111
#define MAP_ADD                 112
#define LOAD_CLASSDEREF         113
#define MATCH_CLASS             114
#define SETUP_ASYNC_WITH        115
#define FORMAT_VALUE            116
#define BUILD_CONST_KEY_MAP     117
#define BUILD_STRING            118
#define LOAD_METHOD             119
#define CALL_METHOD             120
#define LIST_EXTEND             121
#define SET_UPDATE              122
#define DICT_MERGE              123
#define DICT_UPDATE             124
#define HAVE_REGISTERS          125
#define BINARY_ADD_REG          125
#define BINARY_AND_REG          126
#define BINARY_FLOOR_DIVIDE_REG 127
#define BINARY_LSHIFT_REG       128
#define BINARY_MATRIX_MULTIPLY_REG 129
#define BINARY_MODULO_REG       130
#define BINARY_MULTIPLY_REG     131
#define BINARY_OR_REG           132
#define BINARY_POWER_REG        133
#define BINARY_RSHIFT_REG       134
#define BINARY_SUBSCR_REG       135
#define BINARY_SUBTRACT_REG     136
#define BINARY_TRUE_DIVIDE_REG  137
#define BINARY_XOR_REG          138
#define RETURN_VALUE_REG        139
#define LOAD_CONST_REG          140
#define LOAD_GLOBAL_REG         141
#define LOAD_FAST_REG           142
#define STORE_FAST_REG          143
#define STORE_GLOBAL_REG        144
#define COMPARE_OP_REG          145
#define IS_OP_REG               146
#define CONTAINS_OP_REG         147
#define JUMP_IF_FALSE_REG       148
#define JUMP_IF_TRUE_REG        149
#define UNARY_INVERT_REG        150
#define UNARY_NEGATIVE_REG      151
#define UNARY_NOT_REG           152
#define UNARY_POSITIVE_REG      153
#define BUILD_TUPLE_REG         154
#define BUILD_MAP_REG           155
#define BUILD_LIST_REG          156
#define LIST_EXTEND_REG         157
#define CALL_FUNCTION_REG       158
#define CALL_FUNCTION_KW_REG    159
#define CALL_FUNCTION_EX_REG    160
#define INPLACE_ADD_REG         161
#define INPLACE_AND_REG         162
#define INPLACE_FLOOR_DIVIDE_REG 163
#define INPLACE_LSHIFT_REG      164
#define INPLACE_MATRIX_MULTIPLY_REG 165
#define INPLACE_MODULO_REG      166
#define INPLACE_MULTIPLY_REG    167
#define INPLACE_OR_REG          168
#define INPLACE_POWER_REG       169
#define INPLACE_RSHIFT_REG      170
#define INPLACE_SUBTRACT_REG    171
#define INPLACE_TRUE_DIVIDE_REG 172
#define INPLACE_XOR_REG         173
#define LOAD_ATTR_REG           174
#define STORE_ATTR_REG          175
#define DELETE_ATTR_REG         176
#define GET_ITER_REG            177
#define FOR_ITER_REG            178
#define IMPORT_NAME_REG         179
#define BUILD_SET_REG           180
#define DICT_MERGE_REG          181
#define DICT_UPDATE_REG         182
#define BUILD_STRING_REG        183
#define FORMAT_VALUE_REG        184
#define RAISE_VARARGS_REG       185
#ifdef NEED_OPCODE_JUMP_TABLES
static uint32_t _PyOpcode_RelativeJump[8] = {
    0U,
    0U,
    1074790416U,
    528384U,
    0U,
    262144U,
    0U,
    0U,
};
static uint32_t _PyOpcode_Jump[8] = {
    0U,
    0U,
    1676673040U,
    528384U,
    0U,
    262144U,
    0U,
    0U,
};
#endif /* OPCODE_TABLES */

/* EXCEPT_HANDLER is a special, implicit block type which is created when
   entering an except handler. It is not an opcode but we define it here
   as we want it to be available to both frameobject.c and ceval.c, while
   remaining private.*/
#define EXCEPT_HANDLER 257

#define HAS_ARG(op) ((op) >= HAVE_ARGUMENT)

#define HAS_REGISTERS(op) ((op) >= HAVE_REGISTERS)

#ifdef __cplusplus
}
#endif
#endif /* !Py_OPCODE_H */
